(()=>{
  const $=id=>document.getElementById(id);
  const text=id=>{const e=$(id);return e?e.value.trim():''};
  const num=id=>{const v=text(id);return v===''?'':Number(v)};
  const exportWorkbook=()=>{
    try{
      if(typeof XLSX==='undefined')throw new Error('مكتبة Excel غير محملة.');
      const wb=XLSX.utils.book_new();
      const rows=[];
      const add=(title,value)=>{rows.push([title]);rows.push([value==null?'':String(value)]);rows.push([])};
      rows.push(['قالب الحقيبة التدريبية - فاب لاب الأحساء']);rows.push([]);
      add('اسم البرنامج التدريبي',text('f_name'));
      add('القسم',$('f_department')?.selectedOptions?.[0]?.text||'');
      add('وصف البرنامج التدريبي',text('f_description'));
      add('نوع البرنامج',text('f_program_type'));
      add('المجال الأساسي',text('f_primary_field'));
      add('المجالات المساندة',text('f_supporting_fields'));
      add('الأجهزة والبرامج',text('f_devices_software'));
      add('أهداف البرنامج',state.objectives.map((o,i)=>(i+1)+'. '+o.text).join('\n'));
      add('المستوى',text('f_level'));
      add('نوع التطبيق العملي',text('f_practical'));
      add('المدة',(num('f_days')||'')+' يوم / '+(num('f_hours')||'')+' ساعة');
      add('الفئة العمرية',(num('f_age_min')||'')+' - '+(num('f_age_max')||''));
      add('الفئة المستهدفة',text('f_target'));
      add('عدد المشاركين',num('f_participants'));
      add('تقسيم المشاركين',text('f_split'));
      add('شروط الالتحاق',text('f_requirements'));
      add('مُعدّ المحتوى العلمي',text('f_author'));
      add('رقم الإصدار وتاريخ التحديث',text('f_version'));
      add('تكلفة المستهلكات',num('f_consumables'));
      add('تكلفة تأسيسية غير متكررة',num('f_setup'));
      add('اعتبارات أخرى',text('f_other'));
      rows.push(['المخرجات وتسليماتها']);
      rows.push(['المخرج','النوع','الوصف','الكمية','الملكية','ما الذي سنقيسه؟','النتيجة المطلوبة','طريقة التحقق']);
      state.outputs.forEach(o=>rows.push([o.name,o.output_type,o.description,o.quantity,o.ownership,o.measurement?.what_to_measure||'',o.measurement?.required_result||'',o.measurement?.verification_method||'']));
      rows.push([]);rows.push(['خطة التنفيذ']);
      rows.push(['اليوم','ماذا سنتعلم؟','المحاور','الأهداف المرتبطة','المخرجات المرتبطة','التنفيذ والمدة','التحقق']);
      state.days.forEach(d=>rows.push([d.day_no,d.what_to_learn,d.topics,(d.objective_ids||[]).map(x=>Number(x)+1).join(', '),(d.output_ids||[]).join(', '),d.execution_duration,d.verification]));
      rows.push([]);rows.push(['الموارد البشرية']);
      rows.push(['المورد','العدد','الخبرة أو الشروط المطلوبة','المهام']);
      state.human.forEach(h=>rows.push([h.resource_type,h.quantity,h.requirements,h.responsibilities]));
      rows.push([]);rows.push(['الاحتياجات المادية والتقنية']);
      rows.push(['الاحتياج','المواصفات','الوحدة','الكمية للفرد/المجموعة','الكمية الإجمالية','ملاحظات']);
      state.material.forEach(m=>rows.push([m.item,m.specifications,m.unit,m.quantity_per_person_group,m.total_quantity,m.notes]));
      rows.push([]);rows.push(['الجاهزية قبل التنفيذ']);
      rows.push(['الفئة','جاهز؟','ما يجب تجهيزه أو التحقق منه','المدة اللازمة قبل التنفيذ','ملاحظات']);
      state.readiness.forEach(r=>rows.push([r.category,r.is_ready?'نعم':'لا',r.preparation_requirements,r.lead_time,r.notes]));
      rows.push([]);rows.push(['المرفقات']);
      rows.push(['نوع المرفق','اسم الملف']);
      Object.keys(state.attachments||{}).forEach(k=>{const f=state.attachments[k];if(f)rows.push([k,f.name])});
      const ws=XLSX.utils.aoa_to_sheet(rows);
      ws['!cols']=[{wch:32},{wch:28},{wch:42},{wch:18},{wch:18},{wch:30},{wch:30},{wch:32}];
      ws['!rtl']=true;
      for(const cell of Object.keys(ws)){if(cell[0]==='!')continue;ws[cell].s={alignment:{wrapText:true,vertical:'top',horizontal:'right'}};}
      if(ws.A1)ws.A1.s={font:{bold:true,sz:18},alignment:{horizontal:'center',vertical:'center'}};
      const range=XLSX.utils.decode_range(ws['!ref']);
      for(let r=0;r<=range.e.r;r++)ws['!rows']??=[];
      ws['!rows'][0]={hpt:30};
      const safeName=(text('f_name')||'الحقيبة التدريبية').replace(/[\\/:*?"<>|]/g,'-').slice(0,80);
      XLSX.writeFile(wb,safeName+'.xlsx');
      const status=$('exportStatus');if(status)status.textContent='تم تصدير الحقيبة بالبيانات بنجاح.';
      if(typeof toast==='function')toast('تم تصدير ملف Excel بالبيانات بنجاح');
    }catch(err){console.error(err);const status=$('exportStatus');if(status)status.textContent='تعذر التصدير: '+(err?.message||err);if(typeof toast==='function')toast('تعذر التصدير: '+(err?.message||err),'error');}
  };
  const bind=()=>{const b=$('exportExcel');if(b){b.onclick=exportWorkbook;b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation()},{capture:true});}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
